/**
 * The release metadata is what tells an older build whether an update can still
 * read its save. It is generated by a script that greps a TypeScript constant
 * out of a source file, which is exactly the arrangement that breaks silently
 * during an unrelated refactor — so the agreement is asserted here.
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { SAVE_VERSION } from '../src/types';

// Vitest runs from the repository root, and the config's `include` globs are
// written relative to it, so this is the same directory in every entry point.
const root = process.cwd();

function generate(): { version: string; saveVersion: number; minSaveVersion: number } {
  const out = join(mkdtempSync(join(tmpdir(), 'everroad-meta-')), 'release-meta.json');
  execFileSync('node', [join(root, 'scripts/build-release-meta.mjs'), out], { cwd: root });
  return JSON.parse(readFileSync(out, 'utf8'));
}

describe('build-release-meta', () => {
  it('publishes the SAVE_VERSION this bundle actually compiles against', () => {
    expect(generate().saveVersion).toBe(SAVE_VERSION);
  });

  it("publishes package.json's version, the one the tag has to match", () => {
    const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
    expect(generate().version).toBe(pkg.version);
  });
});
